spring:
  application:
    name: "scm-workspaces"
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.aocwr.mongodb.net/scmworkspaces?retryWrites=true&w=majority

github-api:
  base-url: https://api.github.com
  token: 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

